language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

# '-' indicates start of a stage job
jobs:
  include:
    - stage: "Quality-Checks"
      name: "Linting"
      script: npm run lint
    - name: "snapshot tests"
      script: npm run test
    - stage: "Build"
      script: npm run build
