language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
    - stage: build
      script: npm run build
