language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: "Quality-Checks"
      name: "Linting"
      script: npm run lint
    - script: npm run test
      name: "snapshot tests"
    - stage: "Build"
      script: npm run build
